[package]
name = "rougelike"
version = "0.1.0"
authors = ["Teo <teodor@dahlknutsen.no>"]
edition = "2018"

[dependencies]
tcod = { version = "0.15", features = ["serialization"] }
rand = "0.3.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
